server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/sigh
    username: postgres
    password: 12345  
 
liquibase:
  enabled: true
  change-log: classpath:liquibase/changelog.xml
  contexts: dev